<?php
/**
 * Sync Import — Upload JSON exported from offline Flask app
 * Accessible to bursar and super_admin
 */
if (!defined('ABSPATH')) exit;
?>
<div class="wrap">
    <h1>Excel Schools — Import Data (JSON)</h1>
    <p>Upload a JSON file exported from the offline Flask application using the <strong>Export Data (JSON)</strong> feature. This will merge the data into the online WordPress portal.</p>

    <?php if (!empty($result_message)) echo $result_message; ?>

    <div class="card" style="max-width:720px; padding:24px; margin-top:20px; border:1px solid #ccd0d4; border-radius:8px;">
        <h2>Upload Exported JSON</h2>
        <form method="POST" enctype="multipart/form-data">
            <?php wp_nonce_field('esm_import_json', 'esm_import_nonce'); ?>
            <table class="form-table">
                <tr>
                    <th scope="row"><label for="json_file">JSON File</label></th>
                    <td>
                        <input type="file" name="json_file" id="json_file" accept=".json" required style="padding:10px; border:1px solid #ccc; border-radius:4px; width:100%; max-width:400px;">
                        <p class="description">Select the <code>sync_export_YYYY-MM-DD.json</code> file generated by the offline app.</p>
                    </td>
                </tr>
            </table>
            <?php submit_button('Upload &amp; Import Data', 'primary', 'esm_import_json_submit'); ?>
        </form>
    </div>

    <div style="margin-top:30px; background:#f0f0f1; padding:20px; border-radius:6px; max-width:720px;">
        <h3>How it works</h3>
        <ol>
            <li>In the offline Flask app, go to <strong>Sync Center → Export Data (JSON)</strong></li>
            <li>Download the generated JSON file</li>
            <li>Upload that file here</li>
            <li>The system will automatically import students, staff, fees, invoices, etc.</li>
        </ol>
        <p><strong>Note:</strong> Only bursars and super admins can perform this operation.</p>
    </div>
</div>
