#!/usr/bin/env python3
"""
remove-onceoff-levies.py
========================
Remove the once-off levies from uploaded students' invoices:

    1. Textbook Levy (Once-off)
    2. Registration Fee (Once-off)

The script also marks every affected learner as "once-off levies already
billed", so the system will NOT add these two fees again when their
invoice is refreshed or regenerated (including new terms).

Usage:
    python remove-onceoff-levies.py            # apply the removal
    python remove-onceoff-levies.py --dry-run  # preview only, no changes
    python remove-onceoff-levies.py --yes      # apply without confirmation

On Windows you can also double-click  remove-onceoff-levies.bat  (it asks
before applying).

The script is safe to run more than once: the second run finds nothing.
Run it on the server computer while the Excel Schools server is stopped,
then start the server again.
"""

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from app import app, db, Student, Invoice, InvoiceItem, update_invoice_status  # noqa: E402

# Descriptions generated by the billing engine for once-off levies.
LEVY_PATTERNS = ('textbook levy', 'registration fee')


def main() -> int:
    dry_run = '--dry-run' in sys.argv
    auto_yes = '--yes' in sys.argv

    with app.app_context():
        # 1) Find every once-off levy line on any invoice.
        items = (
            InvoiceItem.query
            .filter(db.or_(
                InvoiceItem.description.ilike('%textbook levy%'),
                InvoiceItem.description.ilike('%registration fee%'),
            ))
            .order_by(InvoiceItem.id)
            .all()
        )

        if not items:
            print('No Textbook Levy / Registration Fee items were found.')
            print('Nothing to remove — the fees are already gone.')
            return 0

        by_invoice = {}
        for item in items:
            by_invoice.setdefault(item.invoice_id, []).append(item)

        invoices = Invoice.query.filter(Invoice.id.in_(list(by_invoice))).all()
        invoice_map = {inv.id: inv for inv in invoices}

        removed_count = 0
        removed_amount = 0.0
        student_ids = set()

        print('=' * 64)
        print(' Once-off levy removal')
        print('=' * 64)
        print(f' Found {len(items)} item(s) on {len(invoices)} invoice(s):')
        for item in items:
            inv = invoice_map.get(item.invoice_id)
            student = db.session.get(Student, inv.student_id) if inv else None
            name = (f'{student.first_name} {student.last_name}'
                    if student else f'student #{inv.student_id if inv else "?"}')
            print(f'   - {item.description:28s} ${item.amount:8.2f}  '
                  f'{name} ({inv.invoice_number if inv else "?"})')
            removed_count += 1
            removed_amount += item.amount or 0.0
            if inv:
                student_ids.add(inv.student_id)

        print('-' * 64)
        print(f' Items to remove : {removed_count}')
        print(f' Total value     : ${removed_amount:,.2f}')
        print(f' Students affected: {len(student_ids)}')

        if dry_run:
            print()
            print('DRY RUN — no changes were made.')
            return 0

        if not auto_yes:
            answer = input('\nApply this removal? [y/N]: ').strip().lower()
            if answer not in ('y', 'yes'):
                print('Cancelled — no changes were made.')
                return 0

        # 2) Delete the levy lines.
        for item in items:
            db.session.delete(item)

        # 3) Recalculate every affected invoice (subtotal, discount, total,
        #    status) and mark the learners so the fees are never billed again.
        for inv in invoices:
            remaining = InvoiceItem.query.filter_by(invoice_id=inv.id).all()
            subtotal = sum(i.amount or 0.0 for i in remaining)
            student = db.session.get(Student, inv.student_id)
            multiplier = student.effective_fee_multiplier if student else 1.0
            discount = subtotal * (1.0 - multiplier)
            inv.subtotal = subtotal
            inv.discount_amount = discount
            inv.total_amount = subtotal - discount
            update_invoice_status(inv)
            if student:
                student.billed_once_off_levies = True
                student.updated_at = __import__('datetime').datetime.utcnow()

        db.session.commit()

        print()
        print(f' DONE — removed {removed_count} item(s) worth '
              f'${removed_amount:,.2f} from {len(invoices)} invoice(s) '
              f'covering {len(student_ids)} learner(s).')
        print(' The learners are marked so Textbook Levy and Registration Fee')
        print(' will not be billed to them again.')
        return 0


if __name__ == '__main__':
    raise SystemExit(main())
